# NumPy – Numerical Python
## 1. Why Learn NumPy?

#### What is it?

NumPy is a powerful Python library for numerical computations. It provides fast and memory-efficient multi-dimensional arrays.

#### Why we need it?

1.Pure Python lists are slow for large datasets.

2.NumPy arrays are optimized for speed and vectorized operations.

3.Most Data Science & Machine Learning libraries (like Pandas, Scikit-Learn, TensorFlow) are built on top of NumPy.

#### Where is it used?

1.Data Analysis

2.Machine Learning & Deep Learning

3.Image Processing (OpenCV, PIL use NumPy arrays)

5.Scientific Computing & Simulations

## 2. Importing NumPy

In [ ]:
import numpy as np

## 3. Arrays vs Python Lists

In [2]:
import numpy as np
import time

# Python list
py_list = [i for i in range(1000000)]

# NumPy array
np_array = np.arange(1000000)

# Time comparison

In [3]:
start = time.time()
sum(py_list)
print("Python list sum time:", time.time() - start)

start = time.time()
np.sum(np_array)
print("NumPy array sum time:", time.time() - start)

Python list sum time: 0.015828847885131836
NumPy array sum time: 0.003997802734375


## 4. Creating Arrays
1.np.arange(start, stop, step)

Purpose: Creates an array of numbers starting from start up to but not including stop, incremented by step.

Your code: np.arange(0, 10, 2)

Start = 0

Stop = 10 (exclusive)

Step = 2

2.np.linspace(start, stop, num)

Purpose: Creates an array of num equally spaced numbers between start and stop (inclusive).

Your code: np.linspace(0, 1, 5)

Start = 0

Stop = 1 (inclusive)

5 numbers evenly spaced

In [4]:
# From list 
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Zeros and Ones
print("Zeros:", np.zeros((2,3)))
print("Ones:", np.ones((2,3)))

# Range and Linspace
print("Arange:", np.arange(0, 10, 2))
print("Linspace:", np.linspace(0, 1, 5))

Array: [1 2 3 4 5]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [5]:
# From list 
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Zeros and Ones
print("Zeros:", np.zeros((1,3)))
print("Ones:", np.ones((1,3)))

# Range and Linspace
print("Arange:", np.arange(0, 7, 3))
print("Linspace:", np.linspace(0, 10, 15))

Array: [1 2 3 4 5]
Zeros: [[0. 0. 0.]]
Ones: [[1. 1. 1.]]
Arange: [0 3 6]
Linspace: [ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


## 5. Array Properties


In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print("Array shape:", arr.shape)
print("Array dtype:", arr.dtype)
print("Array size:", arr.size)
print("Array ndim:", arr.ndim)

Array shape: (2, 3)
Array dtype: int64
Array size: 6
Array ndim: 2


## 6. Indexing and Slicing

In [7]:
arr = np.array([10,20,30,40,50])
print("Element at index 2:", arr[2])
print("Elements from index 1 to 3:", arr[1:4])
print("Elements at indices 0, 2, 4:", arr[[0,2,4]])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])

Element at index 2: 30
Elements from index 1 to 3: [20 30 40]
Elements at indices 0, 2, 4: [10 30 50]
Every second element: [10 30 50]
Reversed array: [50 40 30 20 10]


In [10]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:\n", matrix)
print("Matrix shape:", matrix.shape)
print("Matrix dtype:", matrix.dtype)
print("Matrix size:", matrix.size)
print("Matrix ndim:", matrix.ndim)
print(matrix[0,1]) # element at row 0, col 1
print(matrix[1,:]) # entire row 1
print(matrix[:,2]) # entire col 2
# Matrix operations
print("Transpose:\n", matrix.T)
print("Sum of all elements:", np.sum(matrix))
print("Sum of each column:", np.sum(matrix, axis=0))
print("Sum of each row:", np.sum(matrix, axis=1))
print("Mean of all elements:", np.mean(matrix))
print("Mean of each column:", np.mean(matrix, axis=0))
print("Mean of each row:", np.mean(matrix, axis=1))
print("Element-wise multiplication:\n", matrix * 2)
print("Matrix multiplication:\n", np.dot(matrix, matrix))  

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix shape: (3, 3)
Matrix dtype: int64
Matrix size: 9
Matrix ndim: 2
2
[4 5 6]
[3 6 9]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum of all elements: 45
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]
Mean of all elements: 5.0
Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]
Element-wise multiplication:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Matrix multiplication:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## 7. Operations and Broadcasting

In [11]:
a = np.array([1,2,3]) 
b = np.array([4,5,6])
print("a + b:", a + b)            # Element-wise addition
print("a * b:", a * b)            # Element-wise multiplication
print("a + 10:", a + 10)          # Broadcasting
print("a * 2:", a * 2)            # Broadcasting

a + b: [5 7 9]
a * b: [ 4 10 18]
a + 10: [11 12 13]
a * 2: [2 4 6]


## 8. Mathematical Functions

In [12]:
arr = np.array([1,2,3,4,5])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Square Root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Logarithm:", np.log(arr))

Sum: 15
Mean: 3.0
Max: 5
Min: 1
Standard Deviation: 1.4142135623730951
Variance: 2.0
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


## 9. Reshaping Arrays

In [13]:
arr = np.arange(1, 13)
reshaped = arr.reshape((3,4))
print("Original array:", arr)
print("Reshaped array (3x4):\n", reshaped)
flattened = reshaped.flatten()
print("Flattened array:", flattened)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [23]:
ar= np.arange(1,10)
arr=ar.reshape(3,3)
print(arr[1,:])

[4 5 6]


In [35]:
import random
arr=np.array(np.random.randint(0,15,(5,5)))
print(arr)
print(arr.min())
print(arr.max())

[[ 4  8  3  2  7]
 [ 9 10  9  2  5]
 [ 2 11  3  4 10]
 [ 9  3 11  1 12]
 [ 2  9  2  8  0]]
0
12
